version: "3.2"
services:

  api:
    depends_on:
      store:
        condition: service_healthy
    build: ./images/api
    container_name: api
    ports:
      - 80:3000
    volumes:
      - ./images/api/src:/usr/app/src
    environment:
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"

  store:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - ./_backup:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./images/Frontend
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./images/Frontend/src:/usr/src/app/src

